### 匿名函数

In [7]:
#匿名函数格式
g = lambda x:x**2
g(5)

25

In [11]:
# 若x=1，则输出A，否则输出B

f1 = lambda x:'A' if x==1 else 'B'
f1(3)

'B'

In [13]:
total = lambda x,y,z: x+2*y + z**2
total(1,2,3)

14

# 数组的索引与切片

In [23]:
import numpy as np

In [24]:
#普通索引
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr[3:5]

array([4, 5])

In [26]:
#倒序
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [27]:
arr[-4:-2] #注意左开右闭

array([6, 7])

In [28]:
#修改元素
arr[5] = 10
arr

array([ 1,  2,  3,  4,  5, 10,  7,  8,  9])

In [29]:
arr_change = arr
arr_change[1:3] = [17,19]   #但是原来的数据arr也发生了改变
print(arr_change)
print(arr)

[ 1 17 19  4  5 10  7  8  9]
[ 1 17 19  4  5 10  7  8  9]


*视图上修改，原来的数据也会发生改变

In [30]:
arr_change_1 = arr.copy()   #不会改变原来的数据

In [31]:
arr_change_1[1:3] = [23,40]
print(arr_change_1)
print(arr)

[ 1 23 40  4  5 10  7  8  9]
[ 1 17 19  4  5 10  7  8  9]


In [32]:
#深度copy 
import copy
arr_change_2 = copy.deepcopy(arr)
arr_change_2

array([ 1, 17, 19,  4,  5, 10,  7,  8,  9])

In [33]:
data = np.array([[2,3,4,5,3,2],
                 [3,2,1,2.4,5],
                 [1,2,3,4,5,6]])
data

<ipython-input-33-f1a5bf3474a8>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  data = np.array([[2,3,4,5,3,2],


array([list([2, 3, 4, 5, 3, 2]), list([3, 2, 1, 2.4, 5]),
       list([1, 2, 3, 4, 5, 6])], dtype=object)

In [34]:
data = np.array([[1,2,3,1.2],
                 [3.1,4,3,2],
                 [3,0.3,5,1]])
data

array([[1. , 2. , 3. , 1.2],
       [3.1, 4. , 3. , 2. ],
       [3. , 0.3, 5. , 1. ]])

In [35]:
#逻辑索引
logic = ~(data>=2)  #取出大于等于2的数
data[logic]

array([1. , 1.2, 0.3, 1. ])

In [36]:
logic_1 = (data >= 2)
data[logic_1]

array([2. , 3. , 3.1, 4. , 3. , 2. , 3. , 5. ])

In [37]:
#逻辑运算
logic_2 = (data>=2) & (data <=5)
data[logic_2]

array([2. , 3. , 3.1, 4. , 3. , 2. , 3. , 5. ])

In [38]:
data

array([[1. , 2. , 3. , 1.2],
       [3.1, 4. , 3. , 2. ],
       [3. , 0.3, 5. , 1. ]])

In [39]:
data[[0,-1]][:,[0,1,3]]   #可以理解为交集

array([[1. , 2. , 1.2],
       [3. , 0.3, 1. ]])

In [40]:
#花式索引
#方法1
data[[2,1]]   #输出第三行和第二行

array([[3. , 0.3, 5. , 1. ],
       [3.1, 4. , 3. , 2. ]])

In [41]:
data[[2]]  #输出第三行

array([[3. , 0.3, 5. , 1. ]])

In [42]:
#方法2
data[[2,1],[0,1]]  #输出(2,0)和(1,1)位置的元素

array([3., 4.])

In [43]:
data[:,[2,1]]  #第二列和第三列

array([[3. , 2. ],
       [3. , 4. ],
       [5. , 0.3]])

In [44]:
data[[2,1],:] #第二行和第三行

array([[3. , 0.3, 5. , 1. ],
       [3.1, 4. , 3. , 2. ]])

In [45]:
data[:,[0,1,2]]   #1,2,3列

array([[1. , 2. , 3. ],
       [3.1, 4. , 3. ],
       [3. , 0.3, 5. ]])

In [46]:
data_1 = data[:,[1]]  #取出第二列 
data_2 = data[:,1]
print("data_1 = \n",data_1)
print("data_2 = \n",data_2)
print("data_1的形状为：",data_1.shape)
print("data_2的形状为：",data_2.shape)  #二者的形状不一样

data_1 = 
 [[2. ]
 [4. ]
 [0.3]]
data_2 = 
 [2.  4.  0.3]
data_1的形状为： (3, 1)
data_2的形状为： (3,)


In [47]:
data[[1,-1],[0,1]]  #(1,0)和(-1,1)的元素 (取某个元素)

array([3.1, 0.3])

In [48]:
#花式索引方法
print(data[np.ix_([0,-1],[0,1,3])])
print(np.ix_([0,-1],[0,1,3]))

[[1.  2.  1.2]
 [3.  0.3 1. ]]
(array([[ 0],
       [-1]]), array([[0, 1, 3]]))


In [49]:
#花式索引必须要掌握
data[[0,-1]][:,[0,1,3]]

array([[1. , 2. , 1.2],
       [3. , 0.3, 1. ]])

In [50]:
data[[0,-1]][:,[0,1,3]]

array([[1. , 2. , 1.2],
       [3. , 0.3, 1. ]])

# 数组形状的改变

In [51]:
"""
总结：例如 data.shape -----> (3,4)
     1.reshape(1,12)  不改变原来数组的形状
     2.resize(1,12)   该变了原来数组的形状
     3.arr.shape = (1,12)   改变原来数组的形状  


"""

'\n总结：例如 data.shape -----> (3,4)\n     1.reshape(1,12)  不改变原来数组的形状\n     2.resize(1,12)   该变了原来数组的形状\n     3.arr.shape = (1,12)   改变原来数组的形状  \n\n\n'

In [52]:
import copy
arr = copy.deepcopy(data)
arr

array([[1. , 2. , 3. , 1.2],
       [3.1, 4. , 3. , 2. ],
       [3. , 0.3, 5. , 1. ]])

In [53]:
arr.shape

(3, 4)

### reshape()

In [54]:
arr.reshape(12,1)   #不改变原来的数组的形状——赋值了原来的数组

array([[1. ],
       [2. ],
       [3. ],
       [1.2],
       [3.1],
       [4. ],
       [3. ],
       [2. ],
       [3. ],
       [0.3],
       [5. ],
       [1. ]])

In [55]:
arr

array([[1. , 2. , 3. , 1.2],
       [3.1, 4. , 3. , 2. ],
       [3. , 0.3, 5. , 1. ]])

### resize

In [56]:
arr.resize(12,1)   #直接改变原来数组的形状

In [57]:
arr

array([[1. ],
       [2. ],
       [3. ],
       [1.2],
       [3.1],
       [4. ],
       [3. ],
       [2. ],
       [3. ],
       [0.3],
       [5. ],
       [1. ]])

### arr.shape = (1,12)

In [58]:
arr.shape = (1,12)
arr

array([[1. , 2. , 3. , 1.2, 3.1, 4. , 3. , 2. , 3. , 0.3, 5. , 1. ]])

### ravel() 将数组抹平为一维数组

In [59]:
"""
总结：
     1.ravel   改变原来数组的形状
     2.flatten 不改变原来数组的形状
order = 'F'表示按照列方向抹平
"""

"\n总结：\n     1.ravel   改变原来数组的形状\n     2.flatten 不改变原来数组的形状\norder = 'F'表示按照列方向抹平\n"

In [60]:
arr.shape = (2,6)
arr

array([[1. , 2. , 3. , 1.2, 3.1, 4. ],
       [3. , 2. , 3. , 0.3, 5. , 1. ]])

In [61]:
arr.ravel()    #按照行方向来抹平

array([1. , 2. , 3. , 1.2, 3.1, 4. , 3. , 2. , 3. , 0.3, 5. , 1. ])

In [62]:
arr.ravel(order = 'F')    #按照列方向抹平

array([1. , 3. , 2. , 2. , 3. , 3. , 1.2, 0.3, 3.1, 5. , 4. , 1. ])

In [63]:
arr.flatten()

array([1. , 2. , 3. , 1.2, 3.1, 4. , 3. , 2. , 3. , 0.3, 5. , 1. ])

In [64]:
arr.flatten(order= 'F')

array([1. , 3. , 2. , 2. , 3. , 3. , 1.2, 0.3, 3.1, 5. , 4. , 1. ])

In [65]:
arr.flatten()[1]  = 100
arr

array([[1. , 2. , 3. , 1.2, 3.1, 4. ],
       [3. , 2. , 3. , 0.3, 5. , 1. ]])

In [66]:
arr.ravel()[1] = 100
arr

array([[  1. , 100. ,   3. ,   1.2,   3.1,   4. ],
       [  3. ,   2. ,   3. ,   0.3,   5. ,   1. ]])

In [67]:
arr_t = arr.ravel()
arr_t

array([  1. , 100. ,   3. ,   1.2,   3.1,   4. ,   3. ,   2. ,   3. ,
         0.3,   5. ,   1. ])

In [68]:
arr_t.ndim   #一阶张量

1

In [69]:
arr_t[np.newaxis,:].shape   #对行增加了一个维度   作用：做矩阵乘法

(1, 12)

In [70]:
arr_t[:,np.newaxis].shape   #对列增加了一个维度

(12, 1)

### 合并数组

In [ ]:
"""
合并：
     1.hstack
     2.vstack
 

"""

In [71]:
import numpy as np

In [72]:
arr_1 = np.arange(12).reshape(3,4)
arr_1.shape

(3, 4)

In [73]:
arr_2 = np.arange(6).reshape(-1,2)
arr_2.shape

(3, 2)

In [74]:
#数组合并
np.hstack((arr_1,arr_2))

array([[ 0,  1,  2,  3,  0,  1],
       [ 4,  5,  6,  7,  2,  3],
       [ 8,  9, 10, 11,  4,  5]])

In [75]:
arr_3 = np.arange(24).reshape(-1,4)
arr_3.shape

(6, 4)

In [76]:
np.vstack((arr_1,arr_3))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [77]:
#第三种合并方式
np.concatenate((arr_1,arr_2),axis = 1)

array([[ 0,  1,  2,  3,  0,  1],
       [ 4,  5,  6,  7,  2,  3],
       [ 8,  9, 10, 11,  4,  5]])

In [78]:
np.concatenate((arr_1,arr_3),axis = 0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [79]:
#复制函数
arr_4 = np.array([[2,3],[4,5]])

In [82]:
np.tile(arr_4,(4,1)).shape   #(4,1)将行复制四倍

(8, 2)

In [84]:
np.tile(arr_4,(4,4)).shape

(8, 8)

In [90]:
#三维数组
arr_5 = np.arange(8).reshape(2,2,2)
arr_5.ndim,arr_5.shape,arr_5

(3,
 (2, 2, 2),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]))

In [97]:
#三维数组元素访问
arr_5[0],arr_5[0][1],arr_5[0][1][0],arr_5[1]

(array([[0, 1],
        [2, 3]]),
 array([2, 3]),
 2,
 array([[4, 5],
        [6, 7]]))

# 数组的ufunc广播机制

In [ ]:
"""
ufunc通用函数：
              1.可以对array中的所有元素进行操作


"""

In [2]:
import numpy as np

In [8]:
arb = np.arange(8).reshape(4,2)
arc = np.arange(2)
arb,arc

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]),
 array([0, 1]))

In [14]:
np.tile(arc,(4,1)),arc

(array([[0, 1],
        [0, 1],
        [0, 1],
        [0, 1]]),
 array([0, 1]))

In [16]:
arb + arc   #广播机制相当于调用复制函数

array([[0, 2],
       [2, 4],
       [4, 6],
       [6, 8]])

In [21]:
ard = np.arange(4).reshape(4,1)
ard

array([[0],
       [1],
       [2],
       [3]])

In [22]:
arb +ard

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10]])

# Numpy文件读写

In [42]:
from numpy import genfromtxt
from numpy import loadtxt

In [41]:
#skip_header = 1表示跳过表头或者用数组切片data[1:,:]
data = genfromtxt(r'D:\Users\Desktop\Python code\机器学习实战与算法推导（覃秉丰）\Data\线性回归以及非线性回归\d.csv',delimiter=',',skip_header=1)
data.shape

(100, 2)

In [46]:
#方法2：当数据有缺失值时比较好
data_1 = loadtxt(r'data.csv',delimiter=',')
data_1.shape

(100, 2)

In [49]:
#numpy存储数据
np.savetxt(r'D:\Users\Desktop\Python code\OpenCV\zero.txt',data_1,delimiter=',',fmt='%.3f')

# Numpy字符串处理