### 匿名函数

In [7]:
#匿名函数格式
g = lambda x:x**2
g(5)

25

In [11]:
# 若x=1，则输出A，否则输出B

f1 = lambda x:'A' if x==1 else 'B'
f1(3)

'B'

In [13]:
total = lambda x,y,z: x+2*y + z**2
total(1,2,3)

14

# 数组的索引与切片

In [15]:
import numpy as np

In [17]:
#普通索引
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr[3:5]

array([4, 5])

In [20]:
#倒序
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [22]:
arr[-4:-2] #注意左开右闭

array([6, 7])

In [24]:
#修改元素
arr[5] = 10
arr

array([ 1,  2,  3,  4,  5, 10,  7,  8,  9])

In [30]:
arr_change = arr
arr_change[1:3] = [17,19]   #但是原来的数据arr也发生了改变
print(arr_change)
print(arr)

[ 1 17 19  4  5 10  7  8  9]
[ 1 17 19  4  5 10  7  8  9]


*视图上修改，原来的数据也会发生改变

In [35]:
arr_change_1 = arr.copy()   #不会改变原来的数据

In [34]:
arr_change_1[1:3] = [23,40]
print(arr_change_1)
print(arr)

[ 1 23 40  4  5 10  7  8  9]
[ 1 17 19  4  5 10  7  8  9]


In [41]:
#深度copy 
import copy
arr_change_2 = copy.deepcopy(arr)
arr_change_2

array([ 1, 17, 19,  4,  5, 10,  7,  8,  9])

In [50]:
data = np.array([[2,3,4,5,3,2],
                 [3,2,1,2.4,5],
                 [1,2,3,4,5,6]])
data

<ipython-input-50-f1a5bf3474a8>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  data = np.array([[2,3,4,5,3,2],


array([list([2, 3, 4, 5, 3, 2]), list([3, 2, 1, 2.4, 5]),
       list([1, 2, 3, 4, 5, 6])], dtype=object)

In [53]:
data = np.array([[1,2,3,1.2],
                 [3.1,4,3,2],
                 [3,0.3,5,1]])
data

array([[1. , 2. , 3. , 1.2],
       [3.1, 4. , 3. , 2. ],
       [3. , 0.3, 5. , 1. ]])

In [58]:
#逻辑索引
logic = ~(data>=2)  #取出大于等于2的数
data[logic]

array([1. , 1.2, 0.3, 1. ])

In [62]:
logic_1 = (data >= 2)
data[logic_1]

array([2. , 3. , 3.1, 4. , 3. , 2. , 3. , 5. ])

In [67]:
#逻辑运算
logic_2 = (data>=2) & (data <=5)
data[logic_2]

array([2. , 3. , 3.1, 4. , 3. , 2. , 3. , 5. ])

In [70]:
data

array([[1. , 2. , 3. , 1.2],
       [3.1, 4. , 3. , 2. ],
       [3. , 0.3, 5. , 1. ]])

In [74]:
#花式索引
#方法1
data[[2,1]]   #输出第三行和第二行

array([[3. , 0.3, 5. , 1. ],
       [3.1, 4. , 3. , 2. ]])

In [73]:
data[[2]]  #输出第三行

array([[3. , 0.3, 5. , 1. ]])

In [77]:
#方法2
data[[2,1],[0,1]]  #输出(2,0)和(1,1)位置的元素

array([3., 4.])

In [82]:
data[:,[2,1]]  #第二列和第四列

array([[3. , 2. ],
       [3. , 4. ],
       [5. , 0.3]])

In [84]:
data[[2,1],:] #第二行和第三行

array([[3. , 0.3, 5. , 1. ],
       [3.1, 4. , 3. , 2. ]])

In [86]:
data[:,[0,1,2]]   #1,2,3列

array([[1. , 2. , 3. ],
       [3.1, 4. , 3. ],
       [3. , 0.3, 5. ]])

In [100]:
data_1 = data[:,[1]]  #取出第二列 
data_2 = data[:,1]
print("data_1 = \n",data_1)
print("data_2 = \n",data_2)
print("data_1的形状为：",data_1.shape)
print("data_2的形状为：",data_2.shape)  #二者的形状不一样

data_1 = 
 [[2. ]
 [4. ]
 [0.3]]
data_2 = 
 [2.  4.  0.3]
data_1的形状为： (3, 1)
data_2的形状为： (3,)


In [109]:
data[[1,-1],[0,1]]  #(1,0)和(-1,1)的元素 (取某个元素)

array([3.1, 0.3])

In [104]:
#花式索引方法
print(data[np.ix_([0,-1],[0,1,3])])
print(np.ix_([0,-1],[0,1,3]))

[[1.  2.  1.2]
 [3.  0.3 1. ]]
(array([[ 0],
       [-1]]), array([[0, 1, 3]]))


In [106]:
data[[0,-1]][:,[0,1,3]]

array([[1. , 2. , 1.2],
       [3. , 0.3, 1. ]])

In [110]:
data[[0,-1]][:,[0,1,3]]

array([[1. , 2. , 1.2],
       [3. , 0.3, 1. ]])